### PR TITLE
Refactor and restructure scripts, add detailed logging

### PR DESCRIPTION
**Pull request by hexacyanide**
As of April 13, I have rebased onto PR #30, and have also done the following:
- new COG endpoints have been added in the client-side API
- the ready script for marking the active page has been consolidated into a single script
- arrow functions have been dropped until some slower browsers adopt ES6

----

This pull request addresses issue #28, and accomplishes the following:

- functions are now namespaced to modules
 - debugging can now be traced to specific files
 - the global namespace is no longer used unnecessarily
 - session-related matters are handled independently of the current path
- authorization checks are done regardless of if the DOM has been loaded yet
 - unnecessary requests from unauthenticated users are no longer sent
 - login state indicator handlers are now defined globally rather than per-file
- the API module has been rewritten entirely
 - function naming and error handling conventions have been normalized
 - callbacks now follow a consistent pattern which permits simpler error propagation
 - redundant code across pages have been eliminated (e.g. authorization, query parameters)
 - use of the prototype chain has been introduced
- the libraries [async.js](https://github.com/caolan/async) and [debug.js](https://github.com/visionmedia/debug) have been added
 - repetitive calls to asynchronous functions now can be handled with a single callback
 - chained asynchronous functions can be written to prevent excessive DOM repaints
 - namespaced modules can be debugged independently
 - debug output is no longer shown by default

In general, there are only few visual differences in this PR, and they mostly have to do with optimization. If a user is unauthenticated, attempting to access a restricted page will no longer flash its contents. The loading of assignment/test listings will not briefly display older tests before the entire listing has been received, and the login button has default text (so it is not sizeless during loading). For anything involving a long listing, the client will wait until they have been all received rather than making rapid changes to the document.

I've done some basic testing, but it has not been extensive, so feedback would be appreciated. Since debug output is now off by default, it can be enabled by running the following in your browser console:

    localStorage.debug = 'web-cog:*'

The setting above is persistent unless unset, or if domain-related data is reset, and will enable debug output for all console messages on the `web-cog` namespace. It should look similar to the following:

image

### CODE REVIEW

**Comment by asayler** [comment]
I'll aim to test this out today or tomoor. Taylor is working on a few additions to the history-view of the web interface as well, so if I end up merging those first this may require some minor rebasing to accommodate her changes.

**Comment by asayler** [comment]
I merged this in. Seems to be working well. Thanks!

That said, I can't seem to get the debug output working in Chrome or Firefox (testing on Ubuntu 14.04). I've run `localStorage.debug = 'web-cog:*'` in the console and I can see the value set it the local storage display, but no console logging appears. Thoughts?

**Comment by hexacyanide** [comment]
Looks like I reversed the keywords above; it should actually be:

    localStorage.debug = 'cog-web:*';

**Comment by asayler** [comment]
Ahh. Yep. That did it!

Feel free to add a note to that effect to the README. Or I can.

**Comment by asayler** [comment]
I updated the README with the debug info.

**Comment by asayler** [comment]
Also, I pushed this out into production. But in doing so, I also came across a (probably simple to fix) login bug: https://github.com/asayler/COG-Web/issues/31. I can take a look at it later this week, but feel free to submit a fix if you know what the issue is off the top of your head.

**Pull request merged**
