### PR TITLE
Add colored indicators for test runs

### PR DESCRIPTION
**Pull request by hexacyanide**
This pull request adds the following:

- the status indicator text is now colored
- the run output is now colored

Errors are red, warnings yellow, and successful runs are green.

### CODE REVIEW

**Comment by asayler** [comment]
Thanks. I'm traveling this week, but I'll shoot to get this merged in by early next week.

Also, if you have a moment, can you post a screenshot or two of what the new warning/error coloring looks like? We've discussed a number of options and I'm curious to see what the final arrangement results in on the page as a whole.

**Comment by hexacyanide** [comment]
Here's a screenshot of what's currently in the pull:

image

**Comment by asayler** [comment]
This looks pretty good, but does seem to have at least one minor bug. When the student submits a second (or later) submission without first reloading the page, the "Status" text color does not seem to update for the new status. The background color seems to be okay.

E.g.

first submission: `Status: complete-exception <yellow>`
second submission: `Status: complete <still yellow>`

Thoughts?

**Comment by hexacyanide** [comment]
It looks like it was because `clear_results()` was never called before a new run, so the existing CSS classes would stay on the indicator, while another would be added (it would then have two conflicting styles). Should be resolved in ff3834c.

**Comment by asayler** [comment]
Yep, that fixed it. Thansk!

**Pull request merged**
